# @file
# .travis.yml - Backdrop for Travis CI Integration
#
# Template provided by https://github.com/LionsAd/backdrop_ti.
#
# Based for simpletest upon:
#   https://github.com/sonnym/travis-ci-backdrop-module-example

language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7

matrix:
  fast_finish: true
  allow_failures:
    - php: 7

env:
  global:
    # add composer's global bin directory to the path
    # see: https://github.com/drush-ops/drush#install---composer
    - PATH="$PATH:$HOME/.composer/vendor/bin"

    # Configuration variables.
    - BACKDROP_TI_MODULE_NAME="mentions"
    - BACKDROP_TI_SIMPLETEST_GROUP="Mentions"

    # Define runners and environment vars to include before and after the
    # main runners / environment vars.
    #- BACKDROP_TI_SCRIPT_DIR_BEFORE="./backdrop_ti/before"
    #- BACKDROP_TI_SCRIPT_DIR_AFTER="./backdrop_ti/after"

    # The environment to use, supported are: backdrop-7, backdrop-8
    - BACKDROP_TI_ENVIRONMENT="backdrop-7"

    # Backdrop specific variables.
    - BACKDROP_TI_DB="backdrop_travis_db"
    - BACKDROP_TI_DB_URL="mysql://root:@127.0.0.1/backdrop_travis_db"
    # Note: Do not add a trailing slash here.
    - BACKDROP_TI_WEBSERVER_URL="http://127.0.0.1"
    - BACKDROP_TI_WEBSERVER_PORT="8080"

    # Simpletest specific commandline arguments, the BACKDROP_TI_SIMPLETEST_GROUP is appended at the end.
    - BACKDROP_TI_SIMPLETEST_ARGS="--verbose --color --concurrency 4 --url $BACKDROP_TI_WEBSERVER_URL:$BACKDROP_TI_WEBSERVER_PORT"

    # === Behat specific variables.
    # This is relative to $TRAVIS_BUILD_DIR
    - BACKDROP_TI_BEHAT_DIR="./tests/behat"
    # These arguments are passed to the bin/behat command.
    - BACKDROP_TI_BEHAT_ARGS=""
    # Specify the filename of the behat.yml with the $BACKDROP_TI_BACKDROP_DIR variables.
    - BACKDROP_TI_BEHAT_YML="behat.yml.dist"
    # This is used to setup Xvfb.
    - BACKDROP_TI_BEHAT_SCREENSIZE_COLOR="1280x1024x16"
    # The version of seleniumthat should be used.
    - BACKDROP_TI_BEHAT_SELENIUM_VERSION="2.44"
    # Set BACKDROP_TI_BEHAT_DRIVER to "selenium" to use "firefox" or "chrome" here.
    - BACKDROP_TI_BEHAT_DRIVER="phantomjs"
    - BACKDROP_TI_BEHAT_BROWSER="firefox"

    # PHPUnit specific commandline arguments.
    - BACKDROP_TI_PHPUNIT_ARGS=""
    # Specifying the phpunit-core src/ directory is useful when e.g. a vendor/
    # directory is present in the module directory, which phpunit would then
    # try to find tests in. This option is relative to $TRAVIS_BUILD_DIR.
    #- BACKDROP_TI_PHPUNIT_CORE_SRC_DIRECTORY="./tests/src"

    # Code coverage via coveralls.io
    - BACKDROP_TI_COVERAGE="satooshi/php-coveralls:0.6.*"
    # This needs to match your .coveralls.yml file.
    - BACKDROP_TI_COVERAGE_FILE="build/logs/clover.xml"

    # Debug options
    #- BACKDROP_TI_DEBUG="-x -v"
    # Set to "all" to output all files, set to e.g. "xvfb selenium" or "selenium",
    # etc. to only output those channels.
    #- BACKDROP_TI_DEBUG_FILE_OUTPUT="selenium xvfb webserver"

  matrix:
    # [[[ SELECT ANY OR MORE OPTIONS ]]]
    #- BACKDROP_TI_RUNNERS="phpunit"
    #- BACKDROP_TI_RUNNERS="simpletest"
    #- BACKDROP_TI_RUNNERS="behat"
    #- BACKDROP_TI_RUNNERS="phpunit simpletest behat"
    # Use phpunit-core to test modules with phpunit with Backdrop 8 core.
    #- BACKDROP_TI_RUNNERS="phpunit-core"
    - BACKDROP_TI_RUNNERS="simpletest"

mysql:
  database: backdrop_travis_db
  username: root
  encoding: utf8

before_install:
  - composer self-update
  - cd ./tests
  - composer global require "lionsad/backdrop_ti:1.*"
  - backdrop-ti before_install

install:
  - backdrop-ti install

before_script:
  - backdrop-ti before_script

script:
  - backdrop-ti script

after_script:
  - backdrop-ti after_script

notifications:
  email: false
